# STAGE 2: Run
FROM ubuntu:latest

USER root

# update 
RUN apt update
RUN printf 'y\n1\n\1n' | apt install nodejs
RUN apt install -y npm

# pm2
RUN npm install pm2 -g

# From "builder" stage copy over the artifacts in dist folder to default nginx public folder
COPY /distNew /var/www/html/dist

EXPOSE 80

CMD ["pm2-runtime", "dist/server.js"]