export const environment = {
	production: 			false,
	name: 					'Beatfeel',
	url: 					'https://beatfeel.com/',
	urlApi: 				'http://localhost:8095/v1/',
	urlCdn: 				'https://cdn.beatfeel.com/',
	urlCookie: 				'.beatfeel.com',
	copyright: 				'Beatfeel © ' + new Date().getFullYear(),
	audioMimeTypes: 		'audio/mpeg, audio/mp4',
	photoMimeType: 			'.jpg, .jpeg, .png, .gif, .bmp, .tiff, image/jpeg, image/png, image/gif, image/heic, image/heif, image/webp, video/*, .avi, .mp4, .3gp, .mpeg, .mov, .flv, .f4v, .wmv, .mkv, .webm, .vob, .rm, .rmvb, .m4v, .mpg, .ogv, .ts, .m2ts, .mts, .mxf',
	image: 					'https://cdn.beatfeel.com/common/images/icons/square/icon-512x512.png',
	avatar: 				'https://cdn.beatfeel.com/common/images/user/default/avatar.png',
	background: 			'https://cdn.beatfeel.com/common/images/user/default/background.jpg',
	defaultSongCover: 		'https://cdn.beatfeel.com/common/images/default_song.png',
	defaultPlaylistCover: 	'https://cdn.beatfeel.com/common/images/default_playlist.png',
	defaultPostImage: 		'https://cdn.beatfeel.com/common/images/default_post.png',
	pathPhotos: 			'https://cdn.beatfeel.com/photos/',
	pathVideos: 			'https://cdn.beatfeel.com/videos/',
	pathAudios: 			'https://cdn.beatfeel.com/audios/',
	reCaptcha: 				'6Lf8hTkbAAAAAKcIPskHrfPWeljb_0Wx87UeJOAp',
	authHash: 				'xQ3s1RVrSR',
	ad: 					'<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-5692822538817681" data-ad-slot="5300728600" data-ad-format="auto" data-full-width-responsive="true"></ins>',
	emailPattern: 			/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
	urlRegex: 				/(http|https):\/\/[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])?/g,
	defaultPage: 			'news',
	language: 				1,
	cuantity: 				30,
	contentLengthLimit: 	300,
	maxFileSize: 			50000000,
	maxItemsPerUpload: 		100
};
